### PR TITLE
Update Attributes.elm

### PR DESCRIPTION
**Pull request by rick68**
fix a mistake

### CODE REVIEW

**Comment by evancz** [comment]
Thanks! Do you mind linking to the relevant HTML documentation that shows that the proper name is camel cased?

**Comment by rick68** [comment]
If we do not use `accessKey`, we can not see the attribute `accesskey` in HTML documentation.

**Comment by rehno-lindeque** [comment]
I think http://www.w3.org/html/wg/drafts/html/master/editing.html#dom-accesskey might be what Evan is looking for. The property names seem to be referred to as ["IDL atttributes"](http://stackoverflow.com/a/12355195/167485) (ugh!).

**Comment by evancz** [comment]
Thanks!

**Pull request merged**
