### PR TITLE
Adds `link` tag support

### PR DESCRIPTION
**Pull request by joaomilho**

### CODE REVIEW

**Comment by joaomilho** [comment]
This PR is more of a question: Why don't we have `link` tag support already? I see lots of people asking how to have css inside the reactor debbuger. I can't think of a more natural way to do it than just having a link tag (I've tried in my project and it works fairly well). What am I missing?

**Comment by liuyang1204** [comment]
> I can't think of a more natural way to do it than just having a link tag (I've tried in my project and it works fairly well).

It is not perfect.

The `link` tag generated by this way is inside the `body`, which is a little different from the ones in `head`:

http://stackoverflow.com/questions/1642212/whats-the-difference-if-i-put-css-file-inside-head-or-body

**Comment by joaomilho** [comment]
Well, that's because Elm doesn't expect you to write your HTML container in it. Maybe the solution is not to avoid the `link` tag, but actually to add support for `html`, `meta`...

WDYT?

**Comment by liuyang1204** [comment]
Well, I agree to make this library to support `link`, `html`, `meta`...

What I wanted to state is that I'm still asking a better solution of "how to have css inside the reactor debbuger".

**Comment by joaomilho** [comment]
well, is there any roadmap on Elm in general about that?

**Pull request closed without merging**
