### PR TITLE
server-side rendering

### PR DESCRIPTION
**Pull request by gyzerok**
Sorry for a new PR. I failed previous history. Now this is ready to be merged.

Corresponding PR https://github.com/evancz/virtual-dom/pull/32

### CODE REVIEW

**Comment by eeue56** [comment]
If this is to be added, it shouldn't been in `Html.Server`. It's a helper function that generates a string from `Html` - nothing directly tied to a server.

**Comment by igrep** [comment]
I agree with @eeue56 .
How about simply `Html.String`? Sounds good for `Html.fromString`.

**Comment by gyzerok** [comment]
@eeue56 I just directly follow React way here. They do have `ReactDOMServer` with `renderToString`.

**Comment by gyzerok** [comment]
@igrep I definitely think we need a separate namespace. We may now follow React way of namespacing here and see how it works. Mb the only use case is really server-side usage. What do you think on this?

**Comment by igrep** [comment]
> I definitely think we need a separate namespace.

Yeah, I agree to that. So how about `Html.String` as an alternative? So I meant `Html.String.toString`.

> We may now follow React way of namespacing here and see how it works. Mb the only use case is really server-side usage.

Well... Testing has just flashed across my mind.
Comparing by such as `assertEqual "<div>expected</div>" (Html.String.toString actualHtml)` might make sense.

**Comment by laszlopandy** [comment]
What's wrong with `Html.toString`? I think it should be in the top level module since it is only adding one function, it does not justify a separate module.

**Comment by igrep** [comment]
@laszlopandy Our concern is conflict with `Basics.toString` because we usually `import Html exposing (..)` as the architecture tutorial.
If `toString` is exposed by the top level `Html`, it will be ambiguous.
Any idea on it?

**Comment by gyzerok** [comment]
Maybe `Html.Utils` is an appropriate name?

**Comment by evancz** [comment]
I think the name is not that important. The big questions are around:

  * What are the limitations?
  * The technical stuff that Laszlo described.
  * Are there other alternatives?

Documenting all that would be helpful, but I would decide on the naming when merging and reviewing this stuff.

**Comment by laszlopandy** [comment]
@igrep I am now thinking that this should be in a separate package. Please see the discussion in the virtual-dom PR.

**Comment by gyzerok** [comment]
Sorry for silence here, but currently I am able to work on this mostly on weekend. And I guess we are not in hurry.

**Comment by gyzerok** [comment]
I think this PR and corresponding PR may be close because I'm working on [elm-html-extra](https://github.com/gyzerok/elm-html-extra).

Currently this is not for publishing in Elm package system since it is really a pain now and I'm doing this only for my needs because I'd like to introduce Elm to my company and this is the only weak point so far.

Talking about technical details: `vdom-to-html` is currently successfully used by [Cycle.js](https://github.com/cyclejs/dom) and I've just stole an idea. As far as I know there are no better alternatives for now. I'm going to investigate in limitations while using it, but again it is used in Cycle.js for a while now and seems to be a working solution.

**Pull request closed without merging**
