### PR TITLE
Modified mouse events to capture event data

### PR DESCRIPTION
**Pull request by TheSeamau5**
Mouse events in the DOM API come attached with data (such as the
position of the mouse or which mouse button was pressed, etc...).

Previously, this data was not captured and therefore extra work was
necessary in order to simply get the position of the mouse when an
element was clicked.

This commit changes by being more aligned with the [W3C spec]
(http://www.w3.org/TR/SVG2/interact.html)

This is reflected in the `MouseEvent` type which mirrors the DOM
interface of the same name.

Now, for example, rather than `onMouseDown` having the type:

```elm
onMouseDown : Mailbox.Message -> Attribute
```

it has the type:

```elm
onMouseDown : (MouseEvent -> Mailbox.Message) -> Attribute
```

This pull request would solve [this issue](https://github.com/evancz/elm-html/issues/43) and would allow for the capturing of events such as right-click or the mouse wheel.

### CODE REVIEW

**Comment by TheSeamau5** [comment]
The mouse event type is aligned with the W3C spec.

MouseEvent type:

```elm
type alias MouseEvent =
  { screenX : Int
  , screenY : Int
  , clientX : Int
  , clientY : Int
  , ctrlKey : Bool
  , shiftKey : Bool
  , altKey : Bool
  , metaKey : Bool
  , button : Int
  , buttons : Int
  }
```

DOM MouseEvent Interface:
```webidl
interface MouseEvent : UIEvent {
    readonly    attribute long           screenX;
    readonly    attribute long           screenY;
    readonly    attribute long           clientX;
    readonly    attribute long           clientY;
    readonly    attribute boolean        ctrlKey;
    readonly    attribute boolean        shiftKey;
    readonly    attribute boolean        altKey;
    readonly    attribute boolean        metaKey;
    readonly    attribute unsigned short button;
    readonly    attribute unsigned short buttons;
    readonly    attribute EventTarget?   relatedTarget;
    // Introduced in DOM Level 3
    boolean getModifierState (DOMString keyArg);
};
```

Minus those two last things which deal in DOM elements directly, which is bad.

**Comment by TheSeamau5** [comment]
I've added a couple of useful events that were missing from the API. I put them as seperate commits so that you may cherry pick as you see fit

**Comment by vilterp** [comment]
Any comments on why this was closed without merging @evancz? mouseMove, etc events aren't very useful without it e.g. for things like drag and drop.

**Comment by TheSeamau5** [comment]
I think it's a fair enough choice. I'd personally rather `elm-html` provide these low-level bindings directly but they can be provided as a library purely in Elm. I'll do so whenever I get the time and provide decoders for all sorts of events in the spec.

**Comment by vilterp** [comment]
I don't see how these could be provided by another library — where would such a library insert itself into `elm-html`'s API? I think `elm-html` needs to cover the entire HTML/Dom/Events spec (aside from things that don't make sense in FRP), so stuff like this should be in there. That means lib is going to have a big surface area, but I think that's unavoidable — just look at how big [Dart's HTML library](https://api.dartlang.org/apidocs/channels/be/dartdoc-viewer/dart:html) is. I think they're autogenerating all those classes from the W3C's IDL files (as you've pasted there) or something though.

**Comment by evancz** [comment]
All of elm-html is built on top of the very minimal API in evancz/virtual-dom. If you want to create all sorts of events, you can do it with `VirtualDom.on`. So the functions listed by @TheSeamau5 can be implemented by anyone at any time with any API they want. My goal is to keep elm-html relatively simple and have an easy path to doing fancier stuff if you need it, so I think it's best to put these things in a package.

**Comment by rehno-lindeque** [comment]
Feel free to PR https://github.com/circuithub/elm-html-extra by the way, I'm happy to give push permission too if you've got a large number of changes

**Comment by TheSeamau5** [comment]
@vilterp If you look at the commits, there isn't a single line of JS. It's all in Elm.  The idea, is that `on` allows you to pass in a callback and a JSON decoder. This decoder allows you to get at the event variable and from there with the callback you do whatever you want with it. 

When you get used to it, you even stop using the signals provided by the core library cuz you get more flexibility with this.

**Comment by vilterp** [comment]
Thanks @TheSeamau5 and @evancz; I missed that you could specify a custom decoder for `on`. That'll let me do what I need to do for now; may get around to PR'ing something to elm-html-extra @rehno-lindeque.

I still feel these should be in the library, though — it's what I expect coming from React (see https://facebook.github.io/react/docs/events.html#mouse-events), and seems better than making everyone who wants this data go look at MDN and write their own decoders. However I do realize we're trying to keep the API simple, so I'm not sure what the right compromise is.

**Pull request closed without merging**
