### PR TITLE
Added more support for attributes that take int as input

### PR DESCRIPTION
**Pull request by TheSeamau5**
Added:
* `minlength : Int -> Attribute`

Changed:
* `coords`
    * from : `String -> Attribute`
    * to     : `List Int -> Attribute`

Added the helper functions:
- `intProperty : String -> Int -> Attribute`
- `listIntProperty : String -> List Int -> Attribute`

in order to help clean up the code and remove unnecessary `toString`
calls.

### CODE REVIEW

**Comment by evancz** [comment]
I think this PR should be [split up into a couple changes](https://github.com/elm-lang/core/blob/master/CONTRIBUTING.md#ground-rules) that can be evaluated independently. I'd say lets go for `minLength` but I am not sure about the other changes.

I worry about about having too many opinions in this library, so I'd rather not make the `coords` change in the core. It seems to have [very specific shapes it can take](http://www.w3schools.com/tags/att_area_coords.asp) and I'd like to leave that to other libraries if people want exceptional levels of safety. The goal here is that people can read about stuff on MDN or StackOverflow and translate it to Elm pretty directly, ideally not looking at the docs.

**Comment by TheSeamau5** [comment]
Here, I've reverted the changes to simply add the minlength function. I agree, it is a good idea to split up the PR.

About `coords`, I'm sorry I misunderstood everything that took in ints to also mean everything that took ints and even lists of ints. It just feels slightly weird to have access to an expressive type system and not use it in favor of strings. The same could also be said of things like "dir" that could take a union type instead of the strings "rtl" and "ltr". But then again, you never know how the html spec will grow and the last thing you want to do is update union types forever just cuz the w3c was bored and decided to add attributes.

**Comment by evancz** [comment]
In the code snippet of the `<area>` example, notice that a real type for this would actually deal with many attributes:

```html
<map name="planetmap">
  <area shape="rect" coords="0,0,82,126" href="sun.htm" alt="Sun">
  <area shape="circle" coords="90,58,3" href="mercur.htm" alt="Mercury">
  <area shape="circle" coords="124,58,8" href="venus.htm" alt="Venus">
</map>
```

I would expect to see something like this:

```elm
type Shape
    = Rect Int Int Int Int
    | Circle Int Int Int
    | Polygon (List (Int,Int))
```

That would set both `shape` and `coords` fields. I do not want to get into this business with `elm-html`. Same with the case you mentioned. I'm giving a baseline that is easy to use based on reading whatever crap is online. I do not have the bandwidth to make the subjective judgement in all the possible cases of what a nicer API would be, so I think it's best to make that decision decisively and recommend people make packages that have nicer stuff.

**Comment by evancz** [comment]
Thanks for making this change!

I think the `intProperty` thing was interesting, but I just felt a bit uncomfortable about it. Does it work to set all these properties with ints? Is it better? I wish there was a type signature so we could be more sure about these things.

**Comment by TheSeamau5** [comment]
Turns out that in html, you don't need the quotes if you pass in strings... Out of curiosity, I've googled around about the best practices around this:

* [W3Schools](http://www.w3schools.com/htmL/html_attributes.asp)
* [StackOverflow](http://stackoverflow.com/questions/13056683/html-attribute-with-without-quotes)

It seems like the best practice would be to place the quotes although the browsers know what to do with the ints. I've personally never have had that bug but, if people online are recommending to put the quotes, then perhaps I was wrong with the `intProperty` thing. Maybe it's best not to tempt fate and have to change all the code again from `intProperty` to `stringProperty`.

**Comment by TheSeamau5** [comment]
And, about the types of `coords` and the like... I think I agree with you. I think that we should see elm-html as a sort of base-level library and then everyone is free to layer their own abstractions and safety mechanisms on top. From that perspective, it makes lots of sense. It makes even more sense when you take into account webcomponents where people are making arbitary html tags with all sorts of attributes and types of those attributes. So, perhaps it would be counter-productive to fence people in needlessly with type safety. 

And, yeah, to enforce types you'd have to make this whole API and people would have to look constantly at the docs to find out the types the attributes accept, etc... plus, you'd have to go through the whole spec and make weird judgement calls... headaches...

**Comment by rehno-lindeque** [comment]
On the `intProperty` thing, I think that virtual dom actually treats things set via property as actual DOM properties (e.g. `"className"` is the property, `"class"` is the attribute). I.o.w. I don't think this affects the quotation marks in HTML at all. I recently added an `attribute` function to elm's `virtual-dom` that does explicitly set attribute strings. 

I think `intProperty` would only affect the data that `virtual-dom` stores for doing diffs (maybe ints are faster in that case? I have no idea)

**Comment by TheSeamau5** [comment]
I guess we would need to test it. We could try running a todomvc-like benchmark for each case and see the difference. I suspect that this would probably be in the noise. As in, it feels like the kind of optimizations you'd do in the 70's. I think it's best to focus on improving the algorithms rather than deciding between ints and strings.

**Comment by evancz** [comment]
I don't think it helps decide things here, but you may be interested to know that most (all?) browsers do [string interning](http://en.wikipedia.org/wiki/String_interning). This means that, if a string literal appears in the source code, it goes into some master list somewhere. I have ran benchmarks on how to represent the tags for union types in Elm (ints or strings) and strings is *waaaaaaay* faster. It is shocking.

Point is, JS will surprise you with these things :)

**Comment by TheSeamau5** [comment]
Cool! That's interesting. I didn't know about this string interning stuff. So, if I get this right, in JS, when I say:

```js
var h1 = "Hello World";
var h2 = "Hello World";
```

`h1` and `h2` are pointing to the same value? (as opposed to saying that the values they point to are equivalent)

That makes me wonder something though: do the JS VM's use this trick even for things that aren't strings? As in, if you have an two variables storing object literals with the same values and call `Object.freeze` on them, does that give you a speedup?

Ex:

```js
var obj1 = Object.freeze({x: 1, y: 2});
var obj2 = Object.freeze({x: 1, y: 2});

```

**Comment by rehno-lindeque** [comment]
I don't think numbers in attributes will be affected by string interning if it's a dynamically generated (animated) value though... I don't think this stuff is really worth exploring until we have some large animated benchmark anyway.

**Comment by evancz** [comment]
My understanding is that `Object.freeze` makes things orders of magnitude slower. People use it for testing that their code is pure in development, but I have not heard of people using it in production.

**Comment by rtfeldman** [comment]
We're actually using `Object.freeze` in production, although that's only because we haven't bothered to disable it in production. It's definitely slower, but in our use case it's not enough to be noticeable yet, so there hasn't been any momentum behind that optimization.

**Comment by evancz** [comment]
Interesting, I stand corrected! I think the dream there is that enough people start doing what you guys are doing that the browser vendors take note and write optimizations with that in mind :)

**Comment by Raynos** [comment]
@evancz `Object.freeze` is not slower in modern browsers for about a year now. 

It's not *faster* yet, but its only really slower in old browsers.

**Comment by rtfeldman** [comment]
True of Chrome and Firefox, but it's still very slow in current Safari.

Relevant benchmarks, if anyone's interested: http://jsperf.com/performance-frozen-object/32

**Pull request merged**
